name: aro_repository
description: Repository layer for ARO.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  aro_api:
    path: ../aro_api

dev_dependencies:
  test: ^1.17.9
  build_runner: ^2.0.6
  json_serializable: ^4.1.3